//This file was autogenerated via game_tools/asset_manager/pack
#pragma once

#include "waffle_lib.h"

Sprite sprite_table[SPRITE_COUNT] = {
	[SPRITE_BOAR_MEAT_RAW] = {
		292, 126, 8, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_GUN_GREEN] = {
		455, 134, 12, 3, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_1] = {
		689, 33, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_2] = {
		714, 33, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_3] = {
		739, 33, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_4] = {
		487, 34, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_5] = {
		512, 34, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_6] = {
		664, 33, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BOAR_2_DEATH_0] = {
		497, 57, 18, 18, true, { 13.00, 15.00 }
	},
	[SPRITE_BOAR_2_DEATH_1] = {
		664, 56, 22, 19, true, { 16.00, 16.00 }
	},
	[SPRITE_BOAR_2_DEATH_10] = {
		327, 126, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_11] = {
		352, 126, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_12] = {
		377, 126, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_13] = {
		402, 126, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_14] = {
		427, 126, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_15] = {
		452, 126, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_16] = {
		302, 126, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_2] = {
		294, 59, 27, 16, true, { 21.00, 12.00 }
	},
	[SPRITE_BOAR_2_DEATH_3] = {
		551, 57, 29, 17, true, { 22.00, 13.00 }
	},
	[SPRITE_BOAR_2_DEATH_4] = {
		910, 56, 30, 18, true, { 23.00, 14.00 }
	},
	[SPRITE_BOAR_2_DEATH_5] = {
		990, 53, 32, 19, true, { 24.00, 15.00 }
	},
	[SPRITE_BOAR_2_DEATH_6] = {
		22, 90, 32, 14, true, { 24.00, 10.00 }
	},
	[SPRITE_BOAR_2_DEATH_7] = {
		75, 128, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_8] = {
		50, 128, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_9] = {
		101, 127, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_IDLE_0] = {
		143, 62, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_1] = {
		77, 62, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_10] = {
		193, 61, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_11] = {
		932, 76, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_12] = {
		954, 76, 19, 16, true, { 14.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_13] = {
		236, 78, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_14] = {
		257, 78, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_15] = {
		186, 79, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_16] = {
		67, 80, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_17] = {
		88, 80, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_18] = {
		109, 80, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_19] = {
		910, 76, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_2] = {
		826, 76, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_3] = {
		617, 76, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_4] = {
		595, 76, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_5] = {
		573, 76, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_6] = {
		551, 76, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_7] = {
		990, 74, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_8] = {
		45, 72, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_9] = {
		121, 62, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_SLEEP_0] = {
		908, 110, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_1] = {
		929, 110, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_10] = {
		663, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_11] = {
		558, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_12] = {
		661, 77, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_13] = {
		682, 77, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_14] = {
		703, 77, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_15] = {
		724, 77, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_16] = {
		745, 77, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_17] = {
		766, 77, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_18] = {
		787, 77, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_19] = {
		870, 77, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_2] = {
		698, 110, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_20] = {
		165, 78, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_21] = {
		215, 78, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_22] = {
		600, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_23] = {
		537, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_24] = {
		516, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_25] = {
		495, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_26] = {
		768, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_27] = {
		747, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_28] = {
		740, 110, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_29] = {
		761, 110, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_3] = {
		782, 110, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_4] = {
		656, 110, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_5] = {
		677, 110, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_6] = {
		141, 111, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_7] = {
		642, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_8] = {
		684, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_9] = {
		621, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_0] = {
		99, 62, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_1] = {
		23, 72, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_2] = {
		1, 90, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_3] = {
		579, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_4] = {
		866, 110, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_0] = {
		845, 110, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_1] = {
		726, 94, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_2] = {
		130, 80, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_3] = {
		848, 76, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_4] = {
		639, 76, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_WALK_0] = {
		1, 72, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_WALK_1] = {
		519, 77, 20, 15, true, { 15.00, 11.00 }
	},
	[SPRITE_BOAR_WALK_2] = {
		475, 77, 20, 15, true, { 15.00, 11.00 }
	},
	[SPRITE_BOAR_WALK_3] = {
		497, 77, 20, 15, true, { 15.00, 11.00 }
	},
	[SPRITE_BOAR_WALK_4] = {
		826, 58, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_WALK_5] = {
		171, 60, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_WALK_6] = {
		230, 60, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_WALK_7] = {
		252, 60, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_CABLE_1] = {
		101, 113, 30, 12, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_0] = {
		891, 109, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_1] = {
		997, 108, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_10] = {
		325, 77, 23, 15, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_11] = {
		975, 92, 25, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_12] = {
		375, 77, 23, 15, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_13] = {
		871, 94, 18, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_14] = {
		980, 108, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_15] = {
		810, 94, 19, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_16] = {
		963, 108, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_17] = {
		473, 94, 20, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_18] = {
		1, 107, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_2] = {
		39, 106, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_3] = {
		22, 106, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_4] = {
		124, 97, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_5] = {
		107, 97, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_6] = {
		90, 97, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_7] = {
		891, 77, 17, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_8] = {
		719, 110, 19, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_BRONZE_9] = {
		403, 94, 22, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_0] = {
		73, 97, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_1] = {
		56, 97, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_10] = {
		400, 77, 23, 15, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_11] = {
		325, 94, 25, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_12] = {
		450, 77, 23, 15, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_13] = {
		851, 94, 18, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_14] = {
		185, 96, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_15] = {
		789, 94, 19, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_16] = {
		292, 95, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_17] = {
		1002, 92, 20, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_18] = {
		343, 110, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_2] = {
		360, 110, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_3] = {
		377, 110, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_4] = {
		394, 110, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_5] = {
		411, 110, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_6] = {
		428, 110, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_7] = {
		910, 94, 17, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_8] = {
		824, 110, 19, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_GOLD_9] = {
		379, 94, 22, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_0] = {
		445, 110, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_1] = {
		929, 94, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_10] = {
		350, 77, 23, 15, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_11] = {
		352, 94, 25, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_12] = {
		425, 77, 23, 15, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_13] = {
		831, 94, 18, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_14] = {
		946, 94, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_15] = {
		705, 94, 19, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_16] = {
		151, 95, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_17] = {
		451, 94, 20, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_18] = {
		168, 95, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_2] = {
		207, 95, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_3] = {
		224, 95, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_4] = {
		241, 95, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_5] = {
		258, 95, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_6] = {
		275, 95, 15, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_7] = {
		891, 93, 17, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_8] = {
		803, 110, 19, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_CHESTS_IRON_9] = {
		427, 94, 22, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_GREEN_BULLET_1] = {
		1014, 129, 6, 6, false, { 0.00, 0.00 }
	},
	[SPRITE_GREEN_BULLET_STRETCHED_1] = {
		169, 127, 9, 6, false, { 0.00, 0.00 }
	},
	[SPRITE_GROUND_1] = {
		274, 60, 16, 16, false, { 0.00, 0.00 }
	},
	[SPRITE_HERO_DEAD_0] = {
		976, 1, 13, 26, true, { 6.00, 24.00 }
	},
	[SPRITE_HERO_DEAD_1] = {
		959, 1, 15, 28, true, { 7.00, 24.00 }
	},
	[SPRITE_HERO_DEAD_2] = {
		850, 1, 17, 29, true, { 8.00, 25.00 }
	},
	[SPRITE_HERO_DEAD_3] = {
		706, 1, 19, 30, true, { 9.00, 26.00 }
	},
	[SPRITE_HERO_DEAD_4] = {
		536, 1, 21, 31, true, { 10.00, 26.00 }
	},
	[SPRITE_HERO_DEAD_5] = {
		513, 1, 21, 31, true, { 9.00, 26.00 }
	},
	[SPRITE_HERO_DEAD_6] = {
		764, 1, 22, 29, true, { 10.00, 25.00 }
	},
	[SPRITE_HERO_DEAD_7] = {
		41, 134, 7, 4, true, { 4.00, 25.00 }
	},
	[SPRITE_HERO_DEAD_8] = {
		1, 135, 3, 2, true, { 0.00, 24.00 }
	},
	[SPRITE_HERO_DEAD_9] = {
		189, 127, 1, 1, true, { 0.00, 24.00 }
	},
	[SPRITE_HERO_HIT_0] = {
		427, 35, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_HIT_1] = {
		443, 35, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_IDLE_0] = {
		863, 32, 13, 23, true, { 6.00, 20.00 }
	},
	[SPRITE_HERO_IDLE_1] = {
		848, 32, 13, 23, true, { 6.00, 20.00 }
	},
	[SPRITE_HERO_IDLE_2] = {
		991, 27, 13, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_IDLE_3] = {
		991, 1, 13, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_IDLE_4] = {
		878, 32, 13, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_0] = {
		308, 36, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_1] = {
		908, 32, 12, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_2] = {
		834, 32, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_3] = {
		792, 32, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_4] = {
		411, 35, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_5] = {
		650, 33, 12, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_6] = {
		806, 32, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_7] = {
		820, 32, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_LEFT_0] = {
		459, 35, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_MOVE_LEFT_1] = {
		893, 32, 13, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_LEFT_2] = {
		764, 32, 12, 24, true, { 5.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_LEFT_3] = {
		1006, 1, 13, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_UP_0] = {
		363, 35, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_MOVE_UP_1] = {
		936, 32, 12, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_UP_2] = {
		976, 29, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_UP_3] = {
		1006, 27, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_UP_4] = {
		395, 35, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_MOVE_UP_5] = {
		922, 32, 12, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_UP_6] = {
		959, 31, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_UP_7] = {
		778, 32, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_IRON_1] = {
		1014, 108, 8, 9, false, { 0.00, 0.00 }
	},
	[SPRITE_ITEM_CORN] = {
		126, 127, 5, 4, false, { 0.00, 0.00 }
	},
	[SPRITE_LANDING_POD_YELLOW] = {
		1, 1, 74, 69, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_0] = {
		156, 39, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_1] = {
		162, 111, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_2] = {
		622, 34, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_3] = {
		339, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_4] = {
		356, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_5] = {
		324, 36, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_6] = {
		86, 113, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_0] = {
		141, 39, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_1] = {
		71, 113, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_2] = {
		554, 34, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_3] = {
		373, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_4] = {
		390, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_5] = {
		126, 39, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_6] = {
		56, 113, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_0] = {
		111, 39, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_1] = {
		177, 112, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_2] = {
		571, 34, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_3] = {
		407, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_4] = {
		424, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_5] = {
		96, 39, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_6] = {
		292, 111, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_0] = {
		215, 38, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_1] = {
		277, 111, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_2] = {
		537, 34, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_3] = {
		848, 57, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_4] = {
		441, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_5] = {
		200, 38, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_6] = {
		262, 111, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_0] = {
		279, 37, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_1] = {
		247, 111, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_2] = {
		346, 35, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_3] = {
		458, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_4] = {
		759, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_5] = {
		264, 37, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_6] = {
		232, 111, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_0] = {
		249, 37, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_1] = {
		217, 111, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_2] = {
		605, 34, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_3] = {
		776, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_4] = {
		793, 58, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_5] = {
		234, 37, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_6] = {
		202, 111, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_1] = {
		998, 124, 14, 9, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_10] = {
		984, 124, 12, 10, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_11] = {
		18, 122, 13, 12, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_12] = {
		147, 126, 10, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_13] = {
		469, 134, 3, 3, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_14] = {
		33, 134, 6, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_2] = {
		126, 133, 3, 3, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_3] = {
		474, 134, 2, 3, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_4] = {
		133, 126, 12, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_5] = {
		1014, 119, 9, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_6] = {
		943, 132, 4, 4, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_7] = {
		159, 126, 8, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_8] = {
		478, 125, 13, 9, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_9] = {
		943, 125, 3, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_CORN_0] = {
		462, 110, 14, 14, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_CORN_1] = {
		808, 77, 14, 15, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_CORN_2] = {
		309, 77, 14, 16, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_CORN_3] = {
		894, 56, 14, 19, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_0] = {
		544, 135, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_1] = {
		646, 135, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_10] = {
		493, 135, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_2] = {
		404, 134, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_3] = {
		302, 134, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_4] = {
		353, 134, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_5] = {
		595, 135, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_6] = {
		850, 135, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_7] = {
		799, 135, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_8] = {
		748, 135, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_9] = {
		697, 135, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_0] = {
		793, 125, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_1] = {
		843, 125, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_10] = {
		643, 125, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_2] = {
		493, 125, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_3] = {
		192, 126, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_4] = {
		242, 126, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_5] = {
		893, 125, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_6] = {
		543, 125, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_7] = {
		593, 125, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_8] = {
		743, 125, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HUNGER_UI_9] = {
		693, 125, 48, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_IDLE_0] = {
		941, 1, 16, 29, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_IDLE_1] = {
		746, 1, 16, 30, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_IDLE_2] = {
		597, 1, 16, 31, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_IDLE_3] = {
		451, 1, 16, 32, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_IDLE_4] = {
		272, 1, 16, 34, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_IDLE_5] = {
		290, 1, 16, 34, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_IDLE_6] = {
		433, 1, 16, 32, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_IDLE_7] = {
		615, 1, 16, 31, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_MOVE_0] = {
		831, 1, 17, 29, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_MOVE_1] = {
		727, 1, 17, 30, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_MOVE_2] = {
		578, 1, 17, 31, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_MOVE_3] = {
		414, 1, 17, 32, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_MOVE_4] = {
		253, 1, 17, 34, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_MOVE_5] = {
		234, 1, 17, 34, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_MOVE_6] = {
		395, 1, 17, 32, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_MOVE_7] = {
		559, 1, 17, 31, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_0] = {
		887, 1, 16, 29, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_1] = {
		869, 1, 16, 29, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_10] = {
		132, 1, 15, 36, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_11] = {
		115, 1, 15, 36, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_12] = {
		183, 1, 15, 36, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_13] = {
		217, 1, 15, 35, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_14] = {
		469, 1, 16, 32, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_15] = {
		375, 1, 18, 32, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_16] = {
		308, 1, 19, 33, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_17] = {
		487, 1, 24, 31, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_18] = {
		650, 1, 27, 30, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_19] = {
		346, 1, 27, 32, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_2] = {
		923, 1, 16, 29, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_20] = {
		679, 1, 25, 30, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_21] = {
		788, 1, 21, 29, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_22] = {
		811, 1, 18, 29, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_23] = {
		905, 1, 16, 29, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_3] = {
		633, 1, 15, 31, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_4] = {
		329, 1, 15, 33, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_5] = {
		200, 1, 15, 35, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_6] = {
		77, 1, 17, 37, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_7] = {
		96, 1, 17, 36, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_8] = {
		149, 1, 15, 36, false, { 0.00, 0.00 }
	},
	[SPRITE_ROBOT_GATHERER_PLANT_9] = {
		166, 1, 15, 36, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_1] = {
		631, 110, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_2] = {
		506, 110, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_3] = {
		531, 110, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_4] = {
		556, 110, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_5] = {
		606, 110, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_6] = {
		581, 110, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SMALL_BLOCK_1] = {
		33, 122, 15, 10, false, { 0.00, 0.00 }
	},
	[SPRITE_SMALL_BLOCK_2] = {
		967, 124, 15, 10, false, { 0.00, 0.00 }
	},
	[SPRITE_SMALL_BLOCK_3] = {
		1, 123, 15, 10, false, { 0.00, 0.00 }
	},
	[SPRITE_SMALL_BLOCK_4] = {
		950, 124, 15, 10, false, { 0.00, 0.00 }
	},
	[SPRITE_WARRIOR_ATTACK_0] = {
		379, 35, 14, 21, true, { 8.00, 18.00 }
	},
	[SPRITE_WARRIOR_ATTACK_1] = {
		588, 34, 15, 21, true, { 9.00, 18.00 }
	},
	[SPRITE_WARRIOR_ATTACK_2] = {
		810, 58, 14, 17, true, { 5.00, 14.00 }
	},
	[SPRITE_WARRIOR_ATTACK_3] = {
		309, 110, 15, 14, true, { 5.00, 9.00 }
	},
	[SPRITE_WARRIOR_ATTACK_4] = {
		326, 110, 15, 14, true, { 5.00, 10.00 }
	},
	[SPRITE_WARRIOR_DEAD_0] = {
		633, 57, 18, 17, true, { 9.00, 16.00 }
	},
	[SPRITE_WARRIOR_DEAD_1] = {
		475, 57, 20, 18, true, { 10.00, 17.00 }
	},
	[SPRITE_WARRIOR_DEAD_2] = {
		688, 56, 21, 19, true, { 10.00, 18.00 }
	},
	[SPRITE_WARRIOR_DEAD_3] = {
		608, 57, 23, 17, true, { 11.00, 16.00 }
	},
	[SPRITE_WARRIOR_DEAD_4] = {
		582, 57, 24, 17, true, { 11.00, 15.00 }
	},
	[SPRITE_WARRIOR_DEAD_5] = {
		171, 39, 26, 19, true, { 12.00, 16.00 }
	},
	[SPRITE_WARRIOR_DEAD_6] = {
		478, 110, 26, 13, true, { 12.00, 11.00 }
	},
	[SPRITE_WARRIOR_DEAD_7] = {
		180, 127, 7, 6, true, { 3.00, 4.00 }
	},
	[SPRITE_WARRIOR_HIT_0] = {
		878, 56, 14, 19, true, { 8.00, 16.00 }
	},
	[SPRITE_WARRIOR_HIT_1] = {
		743, 56, 14, 19, true, { 8.00, 16.00 }
	},
	[SPRITE_WARRIOR_IDLE_0] = {
		534, 57, 15, 18, true, { 9.00, 15.00 }
	},
	[SPRITE_WARRIOR_IDLE_1] = {
		517, 57, 15, 18, true, { 9.00, 15.00 }
	},
	[SPRITE_WARRIOR_IDLE_2] = {
		77, 40, 15, 19, true, { 9.00, 16.00 }
	},
	[SPRITE_WARRIOR_IDLE_3] = {
		973, 55, 15, 19, true, { 9.00, 16.00 }
	},
	[SPRITE_WARRIOR_IDLE_4] = {
		942, 56, 15, 18, true, { 9.00, 15.00 }
	},
	[SPRITE_WARRIOR_MOVE_LEFT_0] = {
		292, 77, 15, 16, true, { 8.00, 13.00 }
	},
	[SPRITE_WARRIOR_MOVE_LEFT_1] = {
		323, 59, 14, 16, true, { 8.00, 13.00 }
	},
	[SPRITE_WARRIOR_MOVE_LEFT_2] = {
		727, 56, 14, 19, true, { 8.00, 16.00 }
	},
	[SPRITE_WARRIOR_MOVE_LEFT_3] = {
		711, 56, 14, 19, true, { 8.00, 16.00 }
	},
};

Rect hitbox_table[SPRITE_COUNT] = {
	[SPRITE_WARRIOR_ATTACK_2] = {
		0, 8, 18, 20
	},
};

Animation animation_table[ANIM_COUNT] = {
	[ANIM_BOAR_IDLE] = {
		.frames = {
			{ SPRITE_BOAR_IDLE_0, 75 },
			{ SPRITE_BOAR_IDLE_1, 75 },
			{ SPRITE_BOAR_IDLE_2, 75 },
			{ SPRITE_BOAR_IDLE_3, 75 },
			{ SPRITE_BOAR_IDLE_4, 75 },
			{ SPRITE_BOAR_IDLE_5, 75 },
			{ SPRITE_BOAR_IDLE_6, 75 },
			{ SPRITE_BOAR_IDLE_7, 75 },
			{ SPRITE_BOAR_IDLE_8, 75 },
			{ SPRITE_BOAR_IDLE_9, 75 },
			{ SPRITE_BOAR_IDLE_10, 75 },
			{ SPRITE_BOAR_IDLE_11, 75 },
			{ SPRITE_BOAR_IDLE_12, 75 },
			{ SPRITE_BOAR_IDLE_13, 75 },
			{ SPRITE_BOAR_IDLE_14, 75 },
			{ SPRITE_BOAR_IDLE_15, 75 },
			{ SPRITE_BOAR_IDLE_16, 75 },
			{ SPRITE_BOAR_IDLE_17, 75 },
			{ SPRITE_BOAR_IDLE_18, 75 },
			{ SPRITE_BOAR_IDLE_19, 75 }
		},
		.frame_count = 20
	},
	[ANIM_BOAR_TRANSITION_IDLE_TO_SLEEP] = {
		.frames = {
			{ SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_0, 75 },
			{ SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_1, 75 },
			{ SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_2, 75 },
			{ SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_3, 75 },
			{ SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_4, 75 }
		},
		.frame_count = 5
	},
	[ANIM_BOAR_SLEEP] = {
		.frames = {
			{ SPRITE_BOAR_SLEEP_0, 75 },
			{ SPRITE_BOAR_SLEEP_1, 75 },
			{ SPRITE_BOAR_SLEEP_2, 75 },
			{ SPRITE_BOAR_SLEEP_3, 75 },
			{ SPRITE_BOAR_SLEEP_4, 75 },
			{ SPRITE_BOAR_SLEEP_5, 75 },
			{ SPRITE_BOAR_SLEEP_6, 75 },
			{ SPRITE_BOAR_SLEEP_7, 75 },
			{ SPRITE_BOAR_SLEEP_8, 75 },
			{ SPRITE_BOAR_SLEEP_9, 75 },
			{ SPRITE_BOAR_SLEEP_10, 75 },
			{ SPRITE_BOAR_SLEEP_11, 75 },
			{ SPRITE_BOAR_SLEEP_12, 75 },
			{ SPRITE_BOAR_SLEEP_13, 75 },
			{ SPRITE_BOAR_SLEEP_14, 75 },
			{ SPRITE_BOAR_SLEEP_15, 75 },
			{ SPRITE_BOAR_SLEEP_16, 75 },
			{ SPRITE_BOAR_SLEEP_17, 75 },
			{ SPRITE_BOAR_SLEEP_18, 75 },
			{ SPRITE_BOAR_SLEEP_19, 75 },
			{ SPRITE_BOAR_SLEEP_20, 75 },
			{ SPRITE_BOAR_SLEEP_21, 75 },
			{ SPRITE_BOAR_SLEEP_22, 75 },
			{ SPRITE_BOAR_SLEEP_23, 75 },
			{ SPRITE_BOAR_SLEEP_24, 75 },
			{ SPRITE_BOAR_SLEEP_25, 75 },
			{ SPRITE_BOAR_SLEEP_26, 75 },
			{ SPRITE_BOAR_SLEEP_27, 75 },
			{ SPRITE_BOAR_SLEEP_28, 75 },
			{ SPRITE_BOAR_SLEEP_29, 75 }
		},
		.frame_count = 30
	},
	[ANIM_BOAR_TRANSITION_SLEEP_TO_WALK] = {
		.frames = {
			{ SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_0, 75 },
			{ SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_1, 75 },
			{ SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_2, 75 },
			{ SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_3, 75 },
			{ SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_4, 75 }
		},
		.frame_count = 5
	},
	[ANIM_BOAR_WALK] = {
		.frames = {
			{ SPRITE_BOAR_WALK_0, 75 },
			{ SPRITE_BOAR_WALK_1, 75 },
			{ SPRITE_BOAR_WALK_2, 75 },
			{ SPRITE_BOAR_WALK_3, 75 },
			{ SPRITE_BOAR_WALK_4, 75 },
			{ SPRITE_BOAR_WALK_5, 75 },
			{ SPRITE_BOAR_WALK_6, 75 },
			{ SPRITE_BOAR_WALK_7, 75 }
		},
		.frame_count = 8
	},
	[ANIM_WARRIOR_IDLE] = {
		.frames = {
			{ SPRITE_WARRIOR_IDLE_0, 100 },
			{ SPRITE_WARRIOR_IDLE_1, 100 },
			{ SPRITE_WARRIOR_IDLE_2, 100 },
			{ SPRITE_WARRIOR_IDLE_3, 100 },
			{ SPRITE_WARRIOR_IDLE_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_WARRIOR_MOVE_LEFT] = {
		.frames = {
			{ SPRITE_WARRIOR_MOVE_LEFT_0, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_1, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_2, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_3, 100 }
		},
		.frame_count = 4
	},
	[ANIM_WARRIOR_ATTACK] = {
		.frames = {
			{ SPRITE_WARRIOR_ATTACK_0, 100 },
			{ SPRITE_WARRIOR_ATTACK_1, 100 },
			{ SPRITE_WARRIOR_ATTACK_2, 100 },
			{ SPRITE_WARRIOR_ATTACK_3, 100 },
			{ SPRITE_WARRIOR_ATTACK_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_WARRIOR_HIT] = {
		.frames = {
			{ SPRITE_WARRIOR_HIT_0, 100 },
			{ SPRITE_WARRIOR_HIT_1, 100 }
		},
		.frame_count = 2
	},
	[ANIM_WARRIOR_DEAD] = {
		.frames = {
			{ SPRITE_WARRIOR_DEAD_0, 100 },
			{ SPRITE_WARRIOR_DEAD_1, 100 },
			{ SPRITE_WARRIOR_DEAD_2, 100 },
			{ SPRITE_WARRIOR_DEAD_3, 100 },
			{ SPRITE_WARRIOR_DEAD_4, 100 },
			{ SPRITE_WARRIOR_DEAD_5, 100 },
			{ SPRITE_WARRIOR_DEAD_6, 100 },
			{ SPRITE_WARRIOR_DEAD_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_IDLE] = {
		.frames = {
			{ SPRITE_HERO_IDLE_0, 100 },
			{ SPRITE_HERO_IDLE_1, 100 },
			{ SPRITE_HERO_IDLE_2, 100 },
			{ SPRITE_HERO_IDLE_3, 100 },
			{ SPRITE_HERO_IDLE_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_HERO_MOVE_LEFT] = {
		.frames = {
			{ SPRITE_HERO_MOVE_LEFT_0, 100 },
			{ SPRITE_HERO_MOVE_LEFT_1, 100 },
			{ SPRITE_HERO_MOVE_LEFT_2, 100 },
			{ SPRITE_HERO_MOVE_LEFT_3, 100 }
		},
		.frame_count = 4
	},
	[ANIM_HERO_MOVE_DOWN] = {
		.frames = {
			{ SPRITE_HERO_MOVE_DOWN_0, 100 },
			{ SPRITE_HERO_MOVE_DOWN_1, 100 },
			{ SPRITE_HERO_MOVE_DOWN_2, 100 },
			{ SPRITE_HERO_MOVE_DOWN_3, 100 },
			{ SPRITE_HERO_MOVE_DOWN_4, 100 },
			{ SPRITE_HERO_MOVE_DOWN_5, 100 },
			{ SPRITE_HERO_MOVE_DOWN_6, 100 },
			{ SPRITE_HERO_MOVE_DOWN_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_MOVE_UP] = {
		.frames = {
			{ SPRITE_HERO_MOVE_UP_0, 100 },
			{ SPRITE_HERO_MOVE_UP_1, 100 },
			{ SPRITE_HERO_MOVE_UP_2, 100 },
			{ SPRITE_HERO_MOVE_UP_3, 100 },
			{ SPRITE_HERO_MOVE_UP_4, 100 },
			{ SPRITE_HERO_MOVE_UP_5, 100 },
			{ SPRITE_HERO_MOVE_UP_6, 100 },
			{ SPRITE_HERO_MOVE_UP_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_HIT] = {
		.frames = {
			{ SPRITE_HERO_HIT_0, 100 },
			{ SPRITE_HERO_HIT_1, 100 }
		},
		.frame_count = 2
	},
	[ANIM_HERO_DEAD] = {
		.frames = {
			{ SPRITE_HERO_DEAD_0, 100 },
			{ SPRITE_HERO_DEAD_1, 100 },
			{ SPRITE_HERO_DEAD_2, 100 },
			{ SPRITE_HERO_DEAD_3, 100 },
			{ SPRITE_HERO_DEAD_4, 100 },
			{ SPRITE_HERO_DEAD_5, 100 },
			{ SPRITE_HERO_DEAD_6, 100 },
			{ SPRITE_HERO_DEAD_7, 100 },
			{ SPRITE_HERO_DEAD_8, 100 },
			{ SPRITE_HERO_DEAD_9, 100 }
		},
		.frame_count = 10
	},
	[ANIM_BOAR_2_DEATH] = {
		.frames = {
			{ SPRITE_BOAR_2_DEATH_0, 75 },
			{ SPRITE_BOAR_2_DEATH_1, 75 },
			{ SPRITE_BOAR_2_DEATH_2, 75 },
			{ SPRITE_BOAR_2_DEATH_3, 75 },
			{ SPRITE_BOAR_2_DEATH_4, 75 },
			{ SPRITE_BOAR_2_DEATH_5, 75 },
			{ SPRITE_BOAR_2_DEATH_6, 75 },
			{ SPRITE_BOAR_2_DEATH_7, 75 },
			{ SPRITE_BOAR_2_DEATH_8, 75 },
			{ SPRITE_BOAR_2_DEATH_9, 75 },
			{ SPRITE_BOAR_2_DEATH_10, 75 },
			{ SPRITE_BOAR_2_DEATH_11, 75 },
			{ SPRITE_BOAR_2_DEATH_12, 75 },
			{ SPRITE_BOAR_2_DEATH_13, 75 },
			{ SPRITE_BOAR_2_DEATH_14, 75 },
			{ SPRITE_BOAR_2_DEATH_15, 75 },
			{ SPRITE_BOAR_2_DEATH_16, 75 }
		},
		.frame_count = 17
	},
	[ANIM_ROBOT_GATHERER_IDLE] = {
		.frames = {
			{ SPRITE_ROBOT_GATHERER_IDLE_0, 75 },
			{ SPRITE_ROBOT_GATHERER_IDLE_1, 75 },
			{ SPRITE_ROBOT_GATHERER_IDLE_2, 75 },
			{ SPRITE_ROBOT_GATHERER_IDLE_3, 75 },
			{ SPRITE_ROBOT_GATHERER_IDLE_4, 75 },
			{ SPRITE_ROBOT_GATHERER_IDLE_5, 75 },
			{ SPRITE_ROBOT_GATHERER_IDLE_6, 75 },
			{ SPRITE_ROBOT_GATHERER_IDLE_7, 75 }
		},
		.frame_count = 8
	},
	[ANIM_ROBOT_GATHERER_MOVE] = {
		.frames = {
			{ SPRITE_ROBOT_GATHERER_MOVE_0, 75 },
			{ SPRITE_ROBOT_GATHERER_MOVE_1, 75 },
			{ SPRITE_ROBOT_GATHERER_MOVE_2, 75 },
			{ SPRITE_ROBOT_GATHERER_MOVE_3, 75 },
			{ SPRITE_ROBOT_GATHERER_MOVE_4, 75 },
			{ SPRITE_ROBOT_GATHERER_MOVE_5, 75 },
			{ SPRITE_ROBOT_GATHERER_MOVE_6, 75 },
			{ SPRITE_ROBOT_GATHERER_MOVE_7, 75 }
		},
		.frame_count = 8
	},
	[ANIM_ROBOT_GATHERER_PLANT] = {
		.frames = {
			{ SPRITE_ROBOT_GATHERER_PLANT_0, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_1, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_2, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_3, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_4, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_5, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_6, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_7, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_8, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_9, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_10, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_11, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_12, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_13, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_14, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_15, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_16, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_17, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_18, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_19, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_20, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_21, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_22, 75 },
			{ SPRITE_ROBOT_GATHERER_PLANT_23, 75 }
		},
		.frame_count = 24
	},
	[ANIM_CHESTS_GOLD] = {
		.frames = {
			{ SPRITE_CHESTS_GOLD_0, 65 },
			{ SPRITE_CHESTS_GOLD_1, 65 },
			{ SPRITE_CHESTS_GOLD_2, 65 },
			{ SPRITE_CHESTS_GOLD_3, 65 },
			{ SPRITE_CHESTS_GOLD_4, 65 },
			{ SPRITE_CHESTS_GOLD_5, 65 },
			{ SPRITE_CHESTS_GOLD_6, 65 },
			{ SPRITE_CHESTS_GOLD_7, 65 },
			{ SPRITE_CHESTS_GOLD_8, 65 },
			{ SPRITE_CHESTS_GOLD_9, 65 },
			{ SPRITE_CHESTS_GOLD_10, 65 },
			{ SPRITE_CHESTS_GOLD_11, 65 },
			{ SPRITE_CHESTS_GOLD_12, 65 },
			{ SPRITE_CHESTS_GOLD_13, 65 },
			{ SPRITE_CHESTS_GOLD_14, 65 },
			{ SPRITE_CHESTS_GOLD_15, 65 },
			{ SPRITE_CHESTS_GOLD_16, 65 },
			{ SPRITE_CHESTS_GOLD_17, 65 },
			{ SPRITE_CHESTS_GOLD_18, 65 }
		},
		.frame_count = 19
	},
	[ANIM_CHESTS_BRONZE] = {
		.frames = {
			{ SPRITE_CHESTS_BRONZE_0, 65 },
			{ SPRITE_CHESTS_BRONZE_1, 65 },
			{ SPRITE_CHESTS_BRONZE_2, 65 },
			{ SPRITE_CHESTS_BRONZE_3, 65 },
			{ SPRITE_CHESTS_BRONZE_4, 65 },
			{ SPRITE_CHESTS_BRONZE_5, 65 },
			{ SPRITE_CHESTS_BRONZE_6, 65 },
			{ SPRITE_CHESTS_BRONZE_7, 65 },
			{ SPRITE_CHESTS_BRONZE_8, 65 },
			{ SPRITE_CHESTS_BRONZE_9, 65 },
			{ SPRITE_CHESTS_BRONZE_10, 65 },
			{ SPRITE_CHESTS_BRONZE_11, 65 },
			{ SPRITE_CHESTS_BRONZE_12, 65 },
			{ SPRITE_CHESTS_BRONZE_13, 65 },
			{ SPRITE_CHESTS_BRONZE_14, 65 },
			{ SPRITE_CHESTS_BRONZE_15, 65 },
			{ SPRITE_CHESTS_BRONZE_16, 65 },
			{ SPRITE_CHESTS_BRONZE_17, 65 },
			{ SPRITE_CHESTS_BRONZE_18, 65 }
		},
		.frame_count = 19
	},
	[ANIM_CHESTS_IRON] = {
		.frames = {
			{ SPRITE_CHESTS_IRON_0, 65 },
			{ SPRITE_CHESTS_IRON_1, 65 },
			{ SPRITE_CHESTS_IRON_2, 65 },
			{ SPRITE_CHESTS_IRON_3, 65 },
			{ SPRITE_CHESTS_IRON_4, 65 },
			{ SPRITE_CHESTS_IRON_5, 65 },
			{ SPRITE_CHESTS_IRON_6, 65 },
			{ SPRITE_CHESTS_IRON_7, 65 },
			{ SPRITE_CHESTS_IRON_8, 65 },
			{ SPRITE_CHESTS_IRON_9, 65 },
			{ SPRITE_CHESTS_IRON_10, 65 },
			{ SPRITE_CHESTS_IRON_11, 65 },
			{ SPRITE_CHESTS_IRON_12, 65 },
			{ SPRITE_CHESTS_IRON_13, 65 },
			{ SPRITE_CHESTS_IRON_14, 65 },
			{ SPRITE_CHESTS_IRON_15, 65 },
			{ SPRITE_CHESTS_IRON_16, 65 },
			{ SPRITE_CHESTS_IRON_17, 65 },
			{ SPRITE_CHESTS_IRON_18, 65 }
		},
		.frame_count = 19
	}
};