//This file was autogenerated via game_tools/asset_manager/pack
#pragma once

#include "waffle_lib.h"

Sprite sprite_table[SPRITE_COUNT] = {
	[SPRITE_BLOCK_1] = {
		555, 1, 23, 21
	},
	[SPRITE_BLOCK_2] = {
		455, 1, 23, 21
	},
	[SPRITE_BLOCK_3] = {
		480, 1, 23, 21
	},
	[SPRITE_BLOCK_4] = {
		530, 1, 23, 21
	},
	[SPRITE_BLOCK_5] = {
		430, 1, 23, 21
	},
	[SPRITE_BLOCK_6] = {
		505, 1, 23, 21
	},
	[SPRITE_CABLE_1] = {
		455, 24, 30, 12
	},
	[SPRITE_GREEN_BULLET_1] = {
		637, 24, 6, 6
	},
	[SPRITE_GREEN_BULLET_STRETCHED_1] = {
		626, 24, 9, 6
	},
	[SPRITE_GROUND_1] = {
		963, 20, 16, 16
	},
	[SPRITE_GUN_GREEN] = {
		673, 24, 12, 3
	},
	[SPRITE_HERO_DEAD_0] = {
		128, 1, 13, 26
	},
	[SPRITE_HERO_DEAD_1] = {
		111, 1, 15, 28
	},
	[SPRITE_HERO_DEAD_2] = {
		92, 1, 17, 29
	},
	[SPRITE_HERO_DEAD_3] = {
		47, 1, 19, 30
	},
	[SPRITE_HERO_DEAD_4] = {
		24, 1, 21, 31
	},
	[SPRITE_HERO_DEAD_5] = {
		1, 1, 21, 31
	},
	[SPRITE_HERO_DEAD_6] = {
		68, 1, 22, 29
	},
	[SPRITE_HERO_DEAD_7] = {
		658, 24, 7, 4
	},
	[SPRITE_HERO_DEAD_8] = {
		701, 24, 3, 2
	},
	[SPRITE_HERO_DEAD_9] = {
		706, 24, 1, 1
	},
	[SPRITE_HERO_HIT_0] = {
		613, 1, 14, 21
	},
	[SPRITE_HERO_HIT_1] = {
		629, 1, 14, 21
	},
	[SPRITE_HERO_IDLE_0] = {
		329, 1, 13, 23
	},
	[SPRITE_HERO_IDLE_1] = {
		314, 1, 13, 23
	},
	[SPRITE_HERO_IDLE_2] = {
		173, 1, 13, 24
	},
	[SPRITE_HERO_IDLE_3] = {
		143, 1, 13, 24
	},
	[SPRITE_HERO_IDLE_4] = {
		344, 1, 13, 22
	},
	[SPRITE_HERO_MOVE_DOWN_0] = {
		645, 1, 14, 21
	},
	[SPRITE_HERO_MOVE_DOWN_1] = {
		374, 1, 12, 22
	},
	[SPRITE_HERO_MOVE_DOWN_2] = {
		286, 1, 12, 24
	},
	[SPRITE_HERO_MOVE_DOWN_3] = {
		300, 1, 12, 24
	},
	[SPRITE_HERO_MOVE_DOWN_4] = {
		661, 1, 14, 21
	},
	[SPRITE_HERO_MOVE_DOWN_5] = {
		388, 1, 12, 22
	},
	[SPRITE_HERO_MOVE_DOWN_6] = {
		188, 1, 12, 24
	},
	[SPRITE_HERO_MOVE_DOWN_7] = {
		202, 1, 12, 24
	},
	[SPRITE_HERO_MOVE_LEFT_0] = {
		677, 1, 14, 21
	},
	[SPRITE_HERO_MOVE_LEFT_1] = {
		359, 1, 13, 22
	},
	[SPRITE_HERO_MOVE_LEFT_2] = {
		216, 1, 12, 24
	},
	[SPRITE_HERO_MOVE_LEFT_3] = {
		158, 1, 13, 24
	},
	[SPRITE_HERO_MOVE_UP_0] = {
		693, 1, 14, 21
	},
	[SPRITE_HERO_MOVE_UP_1] = {
		402, 1, 12, 22
	},
	[SPRITE_HERO_MOVE_UP_2] = {
		272, 1, 12, 24
	},
	[SPRITE_HERO_MOVE_UP_3] = {
		258, 1, 12, 24
	},
	[SPRITE_HERO_MOVE_UP_4] = {
		709, 1, 14, 21
	},
	[SPRITE_HERO_MOVE_UP_5] = {
		416, 1, 12, 22
	},
	[SPRITE_HERO_MOVE_UP_6] = {
		244, 1, 12, 24
	},
	[SPRITE_HERO_MOVE_UP_7] = {
		230, 1, 12, 24
	},
	[SPRITE_PLANT_1] = {
		569, 24, 14, 9
	},
	[SPRITE_PLANT_10] = {
		555, 24, 12, 10
	},
	[SPRITE_PLANT_11] = {
		850, 22, 13, 12
	},
	[SPRITE_PLANT_12] = {
		614, 24, 10, 8
	},
	[SPRITE_PLANT_13] = {
		687, 24, 3, 3
	},
	[SPRITE_PLANT_14] = {
		645, 24, 6, 5
	},
	[SPRITE_PLANT_2] = {
		692, 24, 3, 3
	},
	[SPRITE_PLANT_3] = {
		697, 24, 2, 3
	},
	[SPRITE_PLANT_4] = {
		600, 24, 12, 8
	},
	[SPRITE_PLANT_5] = {
		1014, 20, 9, 8
	},
	[SPRITE_PLANT_6] = {
		667, 24, 4, 4
	},
	[SPRITE_PLANT_7] = {
		936, 21, 8, 8
	},
	[SPRITE_PLANT_8] = {
		585, 24, 13, 9
	},
	[SPRITE_PLANT_9] = {
		653, 24, 3, 5
	},
	[SPRITE_SHORT_BLOCK_1] = {
		430, 24, 23, 13
	},
	[SPRITE_SHORT_BLOCK_2] = {
		725, 22, 23, 13
	},
	[SPRITE_SHORT_BLOCK_3] = {
		825, 22, 23, 13
	},
	[SPRITE_SHORT_BLOCK_4] = {
		750, 22, 23, 13
	},
	[SPRITE_SHORT_BLOCK_5] = {
		775, 22, 23, 13
	},
	[SPRITE_SHORT_BLOCK_6] = {
		800, 22, 23, 13
	},
	[SPRITE_SMALL_BLOCK_1] = {
		538, 24, 15, 10
	},
	[SPRITE_SMALL_BLOCK_2] = {
		504, 24, 15, 10
	},
	[SPRITE_SMALL_BLOCK_3] = {
		487, 24, 15, 10
	},
	[SPRITE_SMALL_BLOCK_4] = {
		521, 24, 15, 10
	},
	[SPRITE_WARRIOR_ATTACK_0] = {
		597, 1, 14, 21
	},
	[SPRITE_WARRIOR_ATTACK_1] = {
		580, 1, 15, 21
	},
	[SPRITE_WARRIOR_ATTACK_2] = {
		947, 20, 14, 17
	},
	[SPRITE_WARRIOR_ATTACK_3] = {
		891, 21, 15, 14
	},
	[SPRITE_WARRIOR_ATTACK_4] = {
		874, 21, 15, 14
	},
	[SPRITE_WARRIOR_DEAD_0] = {
		998, 1, 18, 17
	},
	[SPRITE_WARRIOR_DEAD_1] = {
		874, 1, 20, 18
	},
	[SPRITE_WARRIOR_DEAD_2] = {
		753, 1, 21, 19
	},
	[SPRITE_WARRIOR_DEAD_3] = {
		973, 1, 23, 17
	},
	[SPRITE_WARRIOR_DEAD_4] = {
		947, 1, 24, 17
	},
	[SPRITE_WARRIOR_DEAD_5] = {
		725, 1, 26, 19
	},
	[SPRITE_WARRIOR_DEAD_6] = {
		908, 21, 26, 13
	},
	[SPRITE_WARRIOR_DEAD_7] = {
		865, 22, 7, 6
	},
	[SPRITE_WARRIOR_HIT_0] = {
		858, 1, 14, 19
	},
	[SPRITE_WARRIOR_HIT_1] = {
		810, 1, 14, 19
	},
	[SPRITE_WARRIOR_IDLE_0] = {
		896, 1, 15, 18
	},
	[SPRITE_WARRIOR_IDLE_1] = {
		913, 1, 15, 18
	},
	[SPRITE_WARRIOR_IDLE_2] = {
		793, 1, 15, 19
	},
	[SPRITE_WARRIOR_IDLE_3] = {
		776, 1, 15, 19
	},
	[SPRITE_WARRIOR_IDLE_4] = {
		930, 1, 15, 18
	},
	[SPRITE_WARRIOR_MOVE_LEFT_0] = {
		981, 20, 15, 16
	},
	[SPRITE_WARRIOR_MOVE_LEFT_1] = {
		998, 20, 14, 16
	},
	[SPRITE_WARRIOR_MOVE_LEFT_2] = {
		842, 1, 14, 19
	},
	[SPRITE_WARRIOR_MOVE_LEFT_3] = {
		826, 1, 14, 19
	},
};

Animation animation_table[ANIM_COUNT] = {
	[ANIM_WARRIOR_IDLE] = {
		.frames = {
			{ SPRITE_WARRIOR_IDLE_0, 100 },
			{ SPRITE_WARRIOR_IDLE_1, 100 },
			{ SPRITE_WARRIOR_IDLE_2, 100 },
			{ SPRITE_WARRIOR_IDLE_3, 100 },
			{ SPRITE_WARRIOR_IDLE_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_WARRIOR_MOVE_LEFT] = {
		.frames = {
			{ SPRITE_WARRIOR_MOVE_LEFT_0, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_1, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_2, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_3, 100 }
		},
		.frame_count = 4
	},
	[ANIM_WARRIOR_ATTACK] = {
		.frames = {
			{ SPRITE_WARRIOR_ATTACK_0, 100 },
			{ SPRITE_WARRIOR_ATTACK_1, 100 },
			{ SPRITE_WARRIOR_ATTACK_2, 100 },
			{ SPRITE_WARRIOR_ATTACK_3, 100 },
			{ SPRITE_WARRIOR_ATTACK_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_WARRIOR_HIT] = {
		.frames = {
			{ SPRITE_WARRIOR_HIT_0, 100 },
			{ SPRITE_WARRIOR_HIT_1, 100 }
		},
		.frame_count = 2
	},
	[ANIM_WARRIOR_DEAD] = {
		.frames = {
			{ SPRITE_WARRIOR_DEAD_0, 100 },
			{ SPRITE_WARRIOR_DEAD_1, 100 },
			{ SPRITE_WARRIOR_DEAD_2, 100 },
			{ SPRITE_WARRIOR_DEAD_3, 100 },
			{ SPRITE_WARRIOR_DEAD_4, 100 },
			{ SPRITE_WARRIOR_DEAD_5, 100 },
			{ SPRITE_WARRIOR_DEAD_6, 100 },
			{ SPRITE_WARRIOR_DEAD_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_IDLE] = {
		.frames = {
			{ SPRITE_HERO_IDLE_0, 100 },
			{ SPRITE_HERO_IDLE_1, 100 },
			{ SPRITE_HERO_IDLE_2, 100 },
			{ SPRITE_HERO_IDLE_3, 100 },
			{ SPRITE_HERO_IDLE_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_HERO_MOVE_LEFT] = {
		.frames = {
			{ SPRITE_HERO_MOVE_LEFT_0, 100 },
			{ SPRITE_HERO_MOVE_LEFT_1, 100 },
			{ SPRITE_HERO_MOVE_LEFT_2, 100 },
			{ SPRITE_HERO_MOVE_LEFT_3, 100 }
		},
		.frame_count = 4
	},
	[ANIM_HERO_MOVE_DOWN] = {
		.frames = {
			{ SPRITE_HERO_MOVE_DOWN_0, 100 },
			{ SPRITE_HERO_MOVE_DOWN_1, 100 },
			{ SPRITE_HERO_MOVE_DOWN_2, 100 },
			{ SPRITE_HERO_MOVE_DOWN_3, 100 },
			{ SPRITE_HERO_MOVE_DOWN_4, 100 },
			{ SPRITE_HERO_MOVE_DOWN_5, 100 },
			{ SPRITE_HERO_MOVE_DOWN_6, 100 },
			{ SPRITE_HERO_MOVE_DOWN_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_MOVE_UP] = {
		.frames = {
			{ SPRITE_HERO_MOVE_UP_0, 100 },
			{ SPRITE_HERO_MOVE_UP_1, 100 },
			{ SPRITE_HERO_MOVE_UP_2, 100 },
			{ SPRITE_HERO_MOVE_UP_3, 100 },
			{ SPRITE_HERO_MOVE_UP_4, 100 },
			{ SPRITE_HERO_MOVE_UP_5, 100 },
			{ SPRITE_HERO_MOVE_UP_6, 100 },
			{ SPRITE_HERO_MOVE_UP_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_HIT] = {
		.frames = {
			{ SPRITE_HERO_HIT_0, 100 },
			{ SPRITE_HERO_HIT_1, 100 }
		},
		.frame_count = 2
	},
	[ANIM_HERO_DEAD] = {
		.frames = {
			{ SPRITE_HERO_DEAD_0, 100 },
			{ SPRITE_HERO_DEAD_1, 100 },
			{ SPRITE_HERO_DEAD_2, 100 },
			{ SPRITE_HERO_DEAD_3, 100 },
			{ SPRITE_HERO_DEAD_4, 100 },
			{ SPRITE_HERO_DEAD_5, 100 },
			{ SPRITE_HERO_DEAD_6, 100 },
			{ SPRITE_HERO_DEAD_7, 100 },
			{ SPRITE_HERO_DEAD_8, 100 },
			{ SPRITE_HERO_DEAD_9, 100 }
		},
		.frame_count = 10
	}
};