//This file was autogenerated via game_tools/asset_manager/pack
#pragma once

#include "waffle_lib.h"

Sprite sprite_table[SPRITE_COUNT] = {
	[SPRITE_BOAR_MEAT_RAW] = {
		261, 62, 8, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_GUN_GREEN] = {
		162, 74, 12, 3, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_1] = {
		455, 1, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_2] = {
		480, 1, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_3] = {
		430, 1, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_4] = {
		505, 1, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_5] = {
		530, 1, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BLOCK_6] = {
		555, 1, 23, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_BOAR_2_DEATH_0] = {
		657, 24, 18, 18, true, { 13.00, 15.00 }
	},
	[SPRITE_BOAR_2_DEATH_1] = {
		492, 24, 22, 19, true, { 16.00, 16.00 }
	},
	[SPRITE_BOAR_2_DEATH_10] = {
		26, 68, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_11] = {
		271, 70, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_12] = {
		271, 62, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_13] = {
		214, 72, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_14] = {
		64, 66, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_15] = {
		89, 66, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_16] = {
		1, 68, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_2] = {
		394, 25, 27, 16, true, { 21.00, 12.00 }
	},
	[SPRITE_BOAR_2_DEATH_3] = {
		728, 24, 29, 17, true, { 22.00, 13.00 }
	},
	[SPRITE_BOAR_2_DEATH_4] = {
		603, 24, 30, 18, true, { 23.00, 14.00 }
	},
	[SPRITE_BOAR_2_DEATH_5] = {
		430, 24, 32, 19, true, { 24.00, 15.00 }
	},
	[SPRITE_BOAR_2_DEATH_6] = {
		437, 45, 32, 14, true, { 24.00, 10.00 }
	},
	[SPRITE_BOAR_2_DEATH_7] = {
		239, 72, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_8] = {
		905, 73, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_2_DEATH_9] = {
		183, 73, 23, 6, true, { 24.00, 2.00 }
	},
	[SPRITE_BOAR_IDLE_0] = {
		882, 43, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_1] = {
		314, 26, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_10] = {
		860, 43, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_11] = {
		838, 43, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_12] = {
		90, 32, 19, 16, true, { 14.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_13] = {
		314, 44, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_14] = {
		335, 44, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_15] = {
		356, 44, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_16] = {
		603, 44, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_17] = {
		624, 44, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_18] = {
		645, 44, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_IDLE_19] = {
		816, 43, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_2] = {
		794, 43, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_3] = {
		772, 43, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_4] = {
		750, 43, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_5] = {
		728, 43, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_6] = {
		394, 43, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_7] = {
		45, 34, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_8] = {
		23, 34, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_IDLE_9] = {
		1, 34, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_SLEEP_0] = {
		651, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_1] = {
		588, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_10] = {
		471, 45, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_11] = {
		534, 45, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_12] = {
		666, 44, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_13] = {
		687, 44, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_14] = {
		133, 45, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_15] = {
		154, 45, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_16] = {
		175, 45, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_17] = {
		196, 45, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_18] = {
		217, 45, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_19] = {
		238, 45, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_2] = {
		546, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_20] = {
		1004, 43, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_21] = {
		259, 45, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_SLEEP_22] = {
		555, 45, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_23] = {
		513, 45, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_24] = {
		938, 60, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_25] = {
		492, 45, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_26] = {
		43, 52, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_27] = {
		22, 52, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_28] = {
		609, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_29] = {
		567, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_3] = {
		504, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_4] = {
		672, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_5] = {
		525, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_6] = {
		462, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_SLEEP_7] = {
		1, 52, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_8] = {
		88, 50, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_SLEEP_9] = {
		67, 50, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_0] = {
		143, 27, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_1] = {
		165, 27, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_2] = {
		280, 45, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_3] = {
		111, 49, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_4] = {
		630, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_0] = {
		483, 61, 19, 13, true, { 14.00, 9.00 }
	},
	[SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_1] = {
		576, 45, 19, 14, true, { 14.00, 10.00 }
	},
	[SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_2] = {
		416, 45, 19, 15, true, { 14.00, 11.00 }
	},
	[SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_3] = {
		187, 27, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_4] = {
		209, 27, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_WALK_0] = {
		231, 27, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_WALK_1] = {
		938, 43, 20, 15, true, { 15.00, 11.00 }
	},
	[SPRITE_BOAR_WALK_2] = {
		982, 43, 20, 15, true, { 15.00, 11.00 }
	},
	[SPRITE_BOAR_WALK_3] = {
		960, 43, 20, 15, true, { 15.00, 11.00 }
	},
	[SPRITE_BOAR_WALK_4] = {
		253, 27, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_WALK_5] = {
		275, 27, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_WALK_6] = {
		111, 31, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_BOAR_WALK_7] = {
		68, 32, 20, 16, true, { 15.00, 12.00 }
	},
	[SPRITE_CABLE_1] = {
		858, 61, 30, 12, false, { 0.00, 0.00 }
	},
	[SPRITE_GREEN_BULLET_1] = {
		114, 65, 6, 6, false, { 0.00, 0.00 }
	},
	[SPRITE_GREEN_BULLET_STRETCHED_1] = {
		416, 62, 9, 6, false, { 0.00, 0.00 }
	},
	[SPRITE_GROUND_1] = {
		904, 43, 16, 16, false, { 0.00, 0.00 }
	},
	[SPRITE_HERO_DEAD_0] = {
		128, 1, 13, 26, true, { 6.00, 24.00 }
	},
	[SPRITE_HERO_DEAD_1] = {
		111, 1, 15, 28, true, { 7.00, 24.00 }
	},
	[SPRITE_HERO_DEAD_2] = {
		92, 1, 17, 29, true, { 8.00, 25.00 }
	},
	[SPRITE_HERO_DEAD_3] = {
		47, 1, 19, 30, true, { 9.00, 26.00 }
	},
	[SPRITE_HERO_DEAD_4] = {
		1, 1, 21, 31, true, { 10.00, 26.00 }
	},
	[SPRITE_HERO_DEAD_5] = {
		24, 1, 21, 31, true, { 9.00, 26.00 }
	},
	[SPRITE_HERO_DEAD_6] = {
		68, 1, 22, 29, true, { 10.00, 25.00 }
	},
	[SPRITE_HERO_DEAD_7] = {
		153, 74, 7, 4, true, { 4.00, 25.00 }
	},
	[SPRITE_HERO_DEAD_8] = {
		708, 75, 3, 2, true, { 0.00, 24.00 }
	},
	[SPRITE_HERO_DEAD_9] = {
		935, 73, 1, 1, true, { 0.00, 24.00 }
	},
	[SPRITE_HERO_HIT_0] = {
		699, 1, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_HIT_1] = {
		795, 1, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_IDLE_0] = {
		314, 1, 13, 23, true, { 6.00, 20.00 }
	},
	[SPRITE_HERO_IDLE_1] = {
		329, 1, 13, 23, true, { 6.00, 20.00 }
	},
	[SPRITE_HERO_IDLE_2] = {
		173, 1, 13, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_IDLE_3] = {
		158, 1, 13, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_IDLE_4] = {
		344, 1, 13, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_0] = {
		763, 1, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_1] = {
		374, 1, 12, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_2] = {
		188, 1, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_3] = {
		300, 1, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_4] = {
		715, 1, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_5] = {
		416, 1, 12, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_6] = {
		272, 1, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_DOWN_7] = {
		258, 1, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_LEFT_0] = {
		811, 1, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_MOVE_LEFT_1] = {
		359, 1, 13, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_LEFT_2] = {
		286, 1, 12, 24, true, { 5.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_LEFT_3] = {
		143, 1, 13, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_UP_0] = {
		779, 1, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_MOVE_UP_1] = {
		388, 1, 12, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_UP_2] = {
		202, 1, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_UP_3] = {
		216, 1, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_UP_4] = {
		747, 1, 14, 21, true, { 7.00, 18.00 }
	},
	[SPRITE_HERO_MOVE_UP_5] = {
		402, 1, 12, 22, true, { 6.00, 19.00 }
	},
	[SPRITE_HERO_MOVE_UP_6] = {
		230, 1, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_HERO_MOVE_UP_7] = {
		244, 1, 12, 24, true, { 6.00, 21.00 }
	},
	[SPRITE_IRON_1] = {
		1012, 60, 8, 9, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_0] = {
		902, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_1] = {
		401, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_2] = {
		614, 1, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_3] = {
		344, 25, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_4] = {
		361, 25, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_5] = {
		857, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COAL_6] = {
		843, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_0] = {
		887, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_1] = {
		693, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_2] = {
		682, 1, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_3] = {
		932, 24, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_4] = {
		915, 24, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_5] = {
		872, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_COPPER_6] = {
		723, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_0] = {
		947, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_1] = {
		738, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_2] = {
		631, 1, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_3] = {
		864, 24, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_4] = {
		898, 24, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_5] = {
		962, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_DIAMOND_6] = {
		708, 60, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_0] = {
		977, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_1] = {
		753, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_2] = {
		665, 1, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_3] = {
		966, 24, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_4] = {
		949, 24, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_5] = {
		842, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_GOLD_6] = {
		768, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_0] = {
		917, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_1] = {
		783, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_2] = {
		580, 1, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_3] = {
		881, 24, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_4] = {
		983, 24, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_5] = {
		932, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_IRON_6] = {
		798, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_0] = {
		992, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_1] = {
		813, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_2] = {
		597, 1, 15, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_3] = {
		830, 24, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_4] = {
		847, 24, 15, 17, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_5] = {
		827, 1, 13, 21, false, { 0.00, 0.00 }
	},
	[SPRITE_ORE_QUARTZ_6] = {
		828, 61, 13, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_1] = {
		183, 62, 14, 9, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_10] = {
		922, 61, 12, 10, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_11] = {
		890, 61, 13, 12, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_12] = {
		228, 62, 10, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_13] = {
		208, 73, 3, 3, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_14] = {
		1012, 71, 6, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_2] = {
		930, 73, 3, 3, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_3] = {
		176, 74, 2, 3, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_4] = {
		214, 62, 12, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_5] = {
		240, 62, 9, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_6] = {
		264, 72, 4, 4, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_7] = {
		251, 62, 8, 8, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_8] = {
		199, 62, 13, 9, false, { 0.00, 0.00 }
	},
	[SPRITE_PLANT_9] = {
		1020, 71, 3, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_0] = {
		602, 76, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_1] = {
		551, 76, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_10] = {
		500, 76, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_2] = {
		449, 76, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_3] = {
		398, 76, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_4] = {
		347, 76, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_5] = {
		296, 76, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_6] = {
		959, 75, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_7] = {
		102, 74, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_8] = {
		653, 76, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_PLAYER_HP_UI_9] = {
		51, 74, 49, 5, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_1] = {
		987, 60, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_2] = {
		376, 61, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_3] = {
		437, 61, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_4] = {
		301, 61, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_5] = {
		326, 61, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SHORT_BLOCK_6] = {
		351, 61, 23, 13, false, { 0.00, 0.00 }
	},
	[SPRITE_SMALL_BLOCK_1] = {
		132, 62, 15, 10, false, { 0.00, 0.00 }
	},
	[SPRITE_SMALL_BLOCK_2] = {
		905, 61, 15, 10, false, { 0.00, 0.00 }
	},
	[SPRITE_SMALL_BLOCK_3] = {
		166, 62, 15, 10, false, { 0.00, 0.00 }
	},
	[SPRITE_SMALL_BLOCK_4] = {
		149, 62, 15, 10, false, { 0.00, 0.00 }
	},
	[SPRITE_WARRIOR_ATTACK_0] = {
		731, 1, 14, 21, true, { 8.00, 18.00 }
	},
	[SPRITE_WARRIOR_ATTACK_1] = {
		648, 1, 15, 21, true, { 9.00, 18.00 }
	},
	[SPRITE_WARRIOR_ATTACK_2] = {
		378, 25, 14, 17, true, { 5.00, 14.00 }
	},
	[SPRITE_WARRIOR_ATTACK_3] = {
		708, 44, 15, 14, true, { 5.00, 9.00 }
	},
	[SPRITE_WARRIOR_ATTACK_4] = {
		377, 44, 15, 14, true, { 5.00, 10.00 }
	},
	[SPRITE_WARRIOR_DEAD_0] = {
		810, 24, 18, 17, true, { 9.00, 16.00 }
	},
	[SPRITE_WARRIOR_DEAD_1] = {
		635, 24, 20, 18, true, { 10.00, 17.00 }
	},
	[SPRITE_WARRIOR_DEAD_2] = {
		516, 24, 21, 19, true, { 10.00, 18.00 }
	},
	[SPRITE_WARRIOR_DEAD_3] = {
		785, 24, 23, 17, true, { 11.00, 16.00 }
	},
	[SPRITE_WARRIOR_DEAD_4] = {
		759, 24, 24, 17, true, { 11.00, 15.00 }
	},
	[SPRITE_WARRIOR_DEAD_5] = {
		464, 24, 26, 19, true, { 12.00, 16.00 }
	},
	[SPRITE_WARRIOR_DEAD_6] = {
		959, 60, 26, 13, true, { 12.00, 11.00 }
	},
	[SPRITE_WARRIOR_DEAD_7] = {
		427, 62, 7, 6, true, { 3.00, 4.00 }
	},
	[SPRITE_WARRIOR_HIT_0] = {
		571, 24, 14, 19, true, { 8.00, 16.00 }
	},
	[SPRITE_WARRIOR_HIT_1] = {
		555, 24, 14, 19, true, { 8.00, 16.00 }
	},
	[SPRITE_WARRIOR_IDLE_0] = {
		677, 24, 15, 18, true, { 9.00, 15.00 }
	},
	[SPRITE_WARRIOR_IDLE_1] = {
		711, 24, 15, 18, true, { 9.00, 15.00 }
	},
	[SPRITE_WARRIOR_IDLE_2] = {
		1007, 22, 15, 19, true, { 9.00, 16.00 }
	},
	[SPRITE_WARRIOR_IDLE_3] = {
		1007, 1, 15, 19, true, { 9.00, 16.00 }
	},
	[SPRITE_WARRIOR_IDLE_4] = {
		694, 24, 15, 18, true, { 9.00, 15.00 }
	},
	[SPRITE_WARRIOR_MOVE_LEFT_0] = {
		297, 27, 15, 16, true, { 8.00, 13.00 }
	},
	[SPRITE_WARRIOR_MOVE_LEFT_1] = {
		922, 43, 14, 16, true, { 8.00, 13.00 }
	},
	[SPRITE_WARRIOR_MOVE_LEFT_2] = {
		587, 24, 14, 19, true, { 8.00, 16.00 }
	},
	[SPRITE_WARRIOR_MOVE_LEFT_3] = {
		539, 24, 14, 19, true, { 8.00, 16.00 }
	},
};

Rect hitbox_table[SPRITE_COUNT] = {
	[SPRITE_WARRIOR_ATTACK_2] = {
		0, 8, 18, 20
	},
};

Animation animation_table[ANIM_COUNT] = {
	[ANIM_BOAR_IDLE] = {
		.frames = {
			{ SPRITE_BOAR_IDLE_0, 75 },
			{ SPRITE_BOAR_IDLE_1, 75 },
			{ SPRITE_BOAR_IDLE_2, 75 },
			{ SPRITE_BOAR_IDLE_3, 75 },
			{ SPRITE_BOAR_IDLE_4, 75 },
			{ SPRITE_BOAR_IDLE_5, 75 },
			{ SPRITE_BOAR_IDLE_6, 75 },
			{ SPRITE_BOAR_IDLE_7, 75 },
			{ SPRITE_BOAR_IDLE_8, 75 },
			{ SPRITE_BOAR_IDLE_9, 75 },
			{ SPRITE_BOAR_IDLE_10, 75 },
			{ SPRITE_BOAR_IDLE_11, 75 },
			{ SPRITE_BOAR_IDLE_12, 75 },
			{ SPRITE_BOAR_IDLE_13, 75 },
			{ SPRITE_BOAR_IDLE_14, 75 },
			{ SPRITE_BOAR_IDLE_15, 75 },
			{ SPRITE_BOAR_IDLE_16, 75 },
			{ SPRITE_BOAR_IDLE_17, 75 },
			{ SPRITE_BOAR_IDLE_18, 75 },
			{ SPRITE_BOAR_IDLE_19, 75 }
		},
		.frame_count = 20
	},
	[ANIM_BOAR_TRANSITION_IDLE_TO_SLEEP] = {
		.frames = {
			{ SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_0, 75 },
			{ SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_1, 75 },
			{ SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_2, 75 },
			{ SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_3, 75 },
			{ SPRITE_BOAR_TRANSITION_IDLE_TO_SLEEP_4, 75 }
		},
		.frame_count = 5
	},
	[ANIM_BOAR_SLEEP] = {
		.frames = {
			{ SPRITE_BOAR_SLEEP_0, 75 },
			{ SPRITE_BOAR_SLEEP_1, 75 },
			{ SPRITE_BOAR_SLEEP_2, 75 },
			{ SPRITE_BOAR_SLEEP_3, 75 },
			{ SPRITE_BOAR_SLEEP_4, 75 },
			{ SPRITE_BOAR_SLEEP_5, 75 },
			{ SPRITE_BOAR_SLEEP_6, 75 },
			{ SPRITE_BOAR_SLEEP_7, 75 },
			{ SPRITE_BOAR_SLEEP_8, 75 },
			{ SPRITE_BOAR_SLEEP_9, 75 },
			{ SPRITE_BOAR_SLEEP_10, 75 },
			{ SPRITE_BOAR_SLEEP_11, 75 },
			{ SPRITE_BOAR_SLEEP_12, 75 },
			{ SPRITE_BOAR_SLEEP_13, 75 },
			{ SPRITE_BOAR_SLEEP_14, 75 },
			{ SPRITE_BOAR_SLEEP_15, 75 },
			{ SPRITE_BOAR_SLEEP_16, 75 },
			{ SPRITE_BOAR_SLEEP_17, 75 },
			{ SPRITE_BOAR_SLEEP_18, 75 },
			{ SPRITE_BOAR_SLEEP_19, 75 },
			{ SPRITE_BOAR_SLEEP_20, 75 },
			{ SPRITE_BOAR_SLEEP_21, 75 },
			{ SPRITE_BOAR_SLEEP_22, 75 },
			{ SPRITE_BOAR_SLEEP_23, 75 },
			{ SPRITE_BOAR_SLEEP_24, 75 },
			{ SPRITE_BOAR_SLEEP_25, 75 },
			{ SPRITE_BOAR_SLEEP_26, 75 },
			{ SPRITE_BOAR_SLEEP_27, 75 },
			{ SPRITE_BOAR_SLEEP_28, 75 },
			{ SPRITE_BOAR_SLEEP_29, 75 }
		},
		.frame_count = 30
	},
	[ANIM_BOAR_TRANSITION_SLEEP_TO_WALK] = {
		.frames = {
			{ SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_0, 75 },
			{ SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_1, 75 },
			{ SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_2, 75 },
			{ SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_3, 75 },
			{ SPRITE_BOAR_TRANSITION_SLEEP_TO_WALK_4, 75 }
		},
		.frame_count = 5
	},
	[ANIM_BOAR_WALK] = {
		.frames = {
			{ SPRITE_BOAR_WALK_0, 75 },
			{ SPRITE_BOAR_WALK_1, 75 },
			{ SPRITE_BOAR_WALK_2, 75 },
			{ SPRITE_BOAR_WALK_3, 75 },
			{ SPRITE_BOAR_WALK_4, 75 },
			{ SPRITE_BOAR_WALK_5, 75 },
			{ SPRITE_BOAR_WALK_6, 75 },
			{ SPRITE_BOAR_WALK_7, 75 }
		},
		.frame_count = 8
	},
	[ANIM_WARRIOR_IDLE] = {
		.frames = {
			{ SPRITE_WARRIOR_IDLE_0, 100 },
			{ SPRITE_WARRIOR_IDLE_1, 100 },
			{ SPRITE_WARRIOR_IDLE_2, 100 },
			{ SPRITE_WARRIOR_IDLE_3, 100 },
			{ SPRITE_WARRIOR_IDLE_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_WARRIOR_MOVE_LEFT] = {
		.frames = {
			{ SPRITE_WARRIOR_MOVE_LEFT_0, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_1, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_2, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_3, 100 }
		},
		.frame_count = 4
	},
	[ANIM_WARRIOR_ATTACK] = {
		.frames = {
			{ SPRITE_WARRIOR_ATTACK_0, 100 },
			{ SPRITE_WARRIOR_ATTACK_1, 100 },
			{ SPRITE_WARRIOR_ATTACK_2, 100 },
			{ SPRITE_WARRIOR_ATTACK_3, 100 },
			{ SPRITE_WARRIOR_ATTACK_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_WARRIOR_HIT] = {
		.frames = {
			{ SPRITE_WARRIOR_HIT_0, 100 },
			{ SPRITE_WARRIOR_HIT_1, 100 }
		},
		.frame_count = 2
	},
	[ANIM_WARRIOR_DEAD] = {
		.frames = {
			{ SPRITE_WARRIOR_DEAD_0, 100 },
			{ SPRITE_WARRIOR_DEAD_1, 100 },
			{ SPRITE_WARRIOR_DEAD_2, 100 },
			{ SPRITE_WARRIOR_DEAD_3, 100 },
			{ SPRITE_WARRIOR_DEAD_4, 100 },
			{ SPRITE_WARRIOR_DEAD_5, 100 },
			{ SPRITE_WARRIOR_DEAD_6, 100 },
			{ SPRITE_WARRIOR_DEAD_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_IDLE] = {
		.frames = {
			{ SPRITE_HERO_IDLE_0, 100 },
			{ SPRITE_HERO_IDLE_1, 100 },
			{ SPRITE_HERO_IDLE_2, 100 },
			{ SPRITE_HERO_IDLE_3, 100 },
			{ SPRITE_HERO_IDLE_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_HERO_MOVE_LEFT] = {
		.frames = {
			{ SPRITE_HERO_MOVE_LEFT_0, 100 },
			{ SPRITE_HERO_MOVE_LEFT_1, 100 },
			{ SPRITE_HERO_MOVE_LEFT_2, 100 },
			{ SPRITE_HERO_MOVE_LEFT_3, 100 }
		},
		.frame_count = 4
	},
	[ANIM_HERO_MOVE_DOWN] = {
		.frames = {
			{ SPRITE_HERO_MOVE_DOWN_0, 100 },
			{ SPRITE_HERO_MOVE_DOWN_1, 100 },
			{ SPRITE_HERO_MOVE_DOWN_2, 100 },
			{ SPRITE_HERO_MOVE_DOWN_3, 100 },
			{ SPRITE_HERO_MOVE_DOWN_4, 100 },
			{ SPRITE_HERO_MOVE_DOWN_5, 100 },
			{ SPRITE_HERO_MOVE_DOWN_6, 100 },
			{ SPRITE_HERO_MOVE_DOWN_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_MOVE_UP] = {
		.frames = {
			{ SPRITE_HERO_MOVE_UP_0, 100 },
			{ SPRITE_HERO_MOVE_UP_1, 100 },
			{ SPRITE_HERO_MOVE_UP_2, 100 },
			{ SPRITE_HERO_MOVE_UP_3, 100 },
			{ SPRITE_HERO_MOVE_UP_4, 100 },
			{ SPRITE_HERO_MOVE_UP_5, 100 },
			{ SPRITE_HERO_MOVE_UP_6, 100 },
			{ SPRITE_HERO_MOVE_UP_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_HIT] = {
		.frames = {
			{ SPRITE_HERO_HIT_0, 100 },
			{ SPRITE_HERO_HIT_1, 100 }
		},
		.frame_count = 2
	},
	[ANIM_HERO_DEAD] = {
		.frames = {
			{ SPRITE_HERO_DEAD_0, 100 },
			{ SPRITE_HERO_DEAD_1, 100 },
			{ SPRITE_HERO_DEAD_2, 100 },
			{ SPRITE_HERO_DEAD_3, 100 },
			{ SPRITE_HERO_DEAD_4, 100 },
			{ SPRITE_HERO_DEAD_5, 100 },
			{ SPRITE_HERO_DEAD_6, 100 },
			{ SPRITE_HERO_DEAD_7, 100 },
			{ SPRITE_HERO_DEAD_8, 100 },
			{ SPRITE_HERO_DEAD_9, 100 }
		},
		.frame_count = 10
	},
	[ANIM_BOAR_2_DEATH] = {
		.frames = {
			{ SPRITE_BOAR_2_DEATH_0, 75 },
			{ SPRITE_BOAR_2_DEATH_1, 75 },
			{ SPRITE_BOAR_2_DEATH_2, 75 },
			{ SPRITE_BOAR_2_DEATH_3, 75 },
			{ SPRITE_BOAR_2_DEATH_4, 75 },
			{ SPRITE_BOAR_2_DEATH_5, 75 },
			{ SPRITE_BOAR_2_DEATH_6, 75 },
			{ SPRITE_BOAR_2_DEATH_7, 75 },
			{ SPRITE_BOAR_2_DEATH_8, 75 },
			{ SPRITE_BOAR_2_DEATH_9, 75 },
			{ SPRITE_BOAR_2_DEATH_10, 75 },
			{ SPRITE_BOAR_2_DEATH_11, 75 },
			{ SPRITE_BOAR_2_DEATH_12, 75 },
			{ SPRITE_BOAR_2_DEATH_13, 75 },
			{ SPRITE_BOAR_2_DEATH_14, 75 },
			{ SPRITE_BOAR_2_DEATH_15, 75 },
			{ SPRITE_BOAR_2_DEATH_16, 75 }
		},
		.frame_count = 17
	}
};