//This file was autogenerated via game_tools/asset_manager/pack
#pragma once

#include "waffle_lib.h"

Sprite sprite_table[SPRITE_COUNT] = {
	[SPRITE_BLOCK_1] = {
		490, 0, 23, 21
	},
	[SPRITE_BLOCK_2] = {
		398, 0, 23, 21
	},
	[SPRITE_BLOCK_3] = {
		421, 0, 23, 21
	},
	[SPRITE_BLOCK_4] = {
		467, 0, 23, 21
	},
	[SPRITE_BLOCK_5] = {
		375, 0, 23, 21
	},
	[SPRITE_BLOCK_6] = {
		444, 0, 23, 21
	},
	[SPRITE_CABLE_1] = {
		773, 18, 30, 12
	},
	[SPRITE_GREEN_BULLET_1] = {
		730, 19, 6, 6
	},
	[SPRITE_GREEN_BULLET_STRETCHED_1] = {
		721, 19, 9, 6
	},
	[SPRITE_GROUND_1] = {
		917, 0, 16, 16
	},
	[SPRITE_GUN_GREEN] = {
		753, 19, 12, 3
	},
	[SPRITE_HERO_DEAD_0] = {
		115, 0, 13, 26
	},
	[SPRITE_HERO_DEAD_1] = {
		100, 0, 15, 28
	},
	[SPRITE_HERO_DEAD_2] = {
		83, 0, 17, 29
	},
	[SPRITE_HERO_DEAD_3] = {
		42, 0, 19, 30
	},
	[SPRITE_HERO_DEAD_4] = {
		21, 0, 21, 31
	},
	[SPRITE_HERO_DEAD_5] = {
		0, 0, 21, 31
	},
	[SPRITE_HERO_DEAD_6] = {
		61, 0, 22, 29
	},
	[SPRITE_HERO_DEAD_7] = {
		742, 19, 7, 4
	},
	[SPRITE_HERO_DEAD_8] = {
		985, 20, 3, 2
	},
	[SPRITE_HERO_DEAD_9] = {
		961, 16, 1, 1
	},
	[SPRITE_HERO_HIT_0] = {
		542, 0, 14, 21
	},
	[SPRITE_HERO_HIT_1] = {
		556, 0, 14, 21
	},
	[SPRITE_HERO_IDLE_0] = {
		288, 0, 13, 23
	},
	[SPRITE_HERO_IDLE_1] = {
		275, 0, 13, 23
	},
	[SPRITE_HERO_IDLE_2] = {
		154, 0, 13, 24
	},
	[SPRITE_HERO_IDLE_3] = {
		128, 0, 13, 24
	},
	[SPRITE_HERO_IDLE_4] = {
		301, 0, 13, 22
	},
	[SPRITE_HERO_MOVE_DOWN_0] = {
		570, 0, 14, 21
	},
	[SPRITE_HERO_MOVE_DOWN_1] = {
		327, 0, 12, 22
	},
	[SPRITE_HERO_MOVE_DOWN_2] = {
		251, 0, 12, 24
	},
	[SPRITE_HERO_MOVE_DOWN_3] = {
		263, 0, 12, 24
	},
	[SPRITE_HERO_MOVE_DOWN_4] = {
		584, 0, 14, 21
	},
	[SPRITE_HERO_MOVE_DOWN_5] = {
		339, 0, 12, 22
	},
	[SPRITE_HERO_MOVE_DOWN_6] = {
		167, 0, 12, 24
	},
	[SPRITE_HERO_MOVE_DOWN_7] = {
		179, 0, 12, 24
	},
	[SPRITE_HERO_MOVE_LEFT_0] = {
		598, 0, 14, 21
	},
	[SPRITE_HERO_MOVE_LEFT_1] = {
		314, 0, 13, 22
	},
	[SPRITE_HERO_MOVE_LEFT_2] = {
		191, 0, 12, 24
	},
	[SPRITE_HERO_MOVE_LEFT_3] = {
		141, 0, 13, 24
	},
	[SPRITE_HERO_MOVE_UP_0] = {
		612, 0, 14, 21
	},
	[SPRITE_HERO_MOVE_UP_1] = {
		351, 0, 12, 22
	},
	[SPRITE_HERO_MOVE_UP_2] = {
		239, 0, 12, 24
	},
	[SPRITE_HERO_MOVE_UP_3] = {
		227, 0, 12, 24
	},
	[SPRITE_HERO_MOVE_UP_4] = {
		626, 0, 14, 21
	},
	[SPRITE_HERO_MOVE_UP_5] = {
		363, 0, 12, 22
	},
	[SPRITE_HERO_MOVE_UP_6] = {
		215, 0, 12, 24
	},
	[SPRITE_HERO_MOVE_UP_7] = {
		203, 0, 12, 24
	},
	[SPRITE_PLANT_1] = {
		682, 19, 14, 9
	},
	[SPRITE_PLANT_10] = {
		670, 19, 12, 10
	},
	[SPRITE_PLANT_11] = {
		940, 16, 13, 12
	},
	[SPRITE_PLANT_12] = {
		907, 17, 10, 8
	},
	[SPRITE_PLANT_13] = {
		765, 19, 3, 3
	},
	[SPRITE_PLANT_14] = {
		736, 19, 6, 5
	},
	[SPRITE_PLANT_2] = {
		768, 19, 3, 3
	},
	[SPRITE_PLANT_3] = {
		836, 18, 2, 3
	},
	[SPRITE_PLANT_4] = {
		709, 19, 12, 8
	},
	[SPRITE_PLANT_5] = {
		1015, 13, 9, 8
	},
	[SPRITE_PLANT_6] = {
		749, 19, 4, 4
	},
	[SPRITE_PLANT_7] = {
		953, 16, 8, 8
	},
	[SPRITE_PLANT_8] = {
		696, 19, 13, 9
	},
	[SPRITE_PLANT_9] = {
		833, 18, 3, 5
	},
	[SPRITE_SHORT_BLOCK_1] = {
		884, 17, 23, 13
	},
	[SPRITE_SHORT_BLOCK_2] = {
		992, 13, 23, 13
	},
	[SPRITE_SHORT_BLOCK_3] = {
		861, 17, 23, 13
	},
	[SPRITE_SHORT_BLOCK_4] = {
		962, 14, 23, 13
	},
	[SPRITE_SHORT_BLOCK_5] = {
		917, 16, 23, 13
	},
	[SPRITE_SHORT_BLOCK_6] = {
		838, 17, 23, 13
	},
	[SPRITE_SMALL_BLOCK_1] = {
		655, 19, 15, 10
	},
	[SPRITE_SMALL_BLOCK_2] = {
		818, 18, 15, 10
	},
	[SPRITE_SMALL_BLOCK_3] = {
		803, 18, 15, 10
	},
	[SPRITE_SMALL_BLOCK_4] = {
		640, 19, 15, 10
	},
	[SPRITE_WARRIOR_ATTACK_0] = {
		528, 0, 14, 21
	},
	[SPRITE_WARRIOR_ATTACK_1] = {
		513, 0, 15, 21
	},
	[SPRITE_WARRIOR_ATTACK_2] = {
		903, 0, 14, 17
	},
	[SPRITE_WARRIOR_ATTACK_3] = {
		977, 0, 15, 14
	},
	[SPRITE_WARRIOR_ATTACK_4] = {
		962, 0, 15, 14
	},
	[SPRITE_WARRIOR_DEAD_0] = {
		885, 0, 18, 17
	},
	[SPRITE_WARRIOR_DEAD_1] = {
		773, 0, 20, 18
	},
	[SPRITE_WARRIOR_DEAD_2] = {
		666, 0, 21, 19
	},
	[SPRITE_WARRIOR_DEAD_3] = {
		862, 0, 23, 17
	},
	[SPRITE_WARRIOR_DEAD_4] = {
		838, 0, 24, 17
	},
	[SPRITE_WARRIOR_DEAD_5] = {
		640, 0, 26, 19
	},
	[SPRITE_WARRIOR_DEAD_6] = {
		992, 0, 26, 13
	},
	[SPRITE_WARRIOR_DEAD_7] = {
		985, 14, 7, 6
	},
	[SPRITE_WARRIOR_HIT_0] = {
		759, 0, 14, 19
	},
	[SPRITE_WARRIOR_HIT_1] = {
		717, 0, 14, 19
	},
	[SPRITE_WARRIOR_IDLE_0] = {
		793, 0, 15, 18
	},
	[SPRITE_WARRIOR_IDLE_1] = {
		808, 0, 15, 18
	},
	[SPRITE_WARRIOR_IDLE_2] = {
		702, 0, 15, 19
	},
	[SPRITE_WARRIOR_IDLE_3] = {
		687, 0, 15, 19
	},
	[SPRITE_WARRIOR_IDLE_4] = {
		823, 0, 15, 18
	},
	[SPRITE_WARRIOR_MOVE_LEFT_0] = {
		933, 0, 15, 16
	},
	[SPRITE_WARRIOR_MOVE_LEFT_1] = {
		948, 0, 14, 16
	},
	[SPRITE_WARRIOR_MOVE_LEFT_2] = {
		745, 0, 14, 19
	},
	[SPRITE_WARRIOR_MOVE_LEFT_3] = {
		731, 0, 14, 19
	},
};

Animation animation_table[ANIM_COUNT] = {
	[ANIM_WARRIOR_IDLE] = {
		.frames = {
			{ SPRITE_WARRIOR_IDLE_0, 100 },
			{ SPRITE_WARRIOR_IDLE_1, 100 },
			{ SPRITE_WARRIOR_IDLE_2, 100 },
			{ SPRITE_WARRIOR_IDLE_3, 100 },
			{ SPRITE_WARRIOR_IDLE_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_WARRIOR_MOVE_LEFT] = {
		.frames = {
			{ SPRITE_WARRIOR_MOVE_LEFT_0, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_1, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_2, 100 },
			{ SPRITE_WARRIOR_MOVE_LEFT_3, 100 }
		},
		.frame_count = 4
	},
	[ANIM_WARRIOR_ATTACK] = {
		.frames = {
			{ SPRITE_WARRIOR_ATTACK_0, 100 },
			{ SPRITE_WARRIOR_ATTACK_1, 100 },
			{ SPRITE_WARRIOR_ATTACK_2, 100 },
			{ SPRITE_WARRIOR_ATTACK_3, 100 },
			{ SPRITE_WARRIOR_ATTACK_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_WARRIOR_HIT] = {
		.frames = {
			{ SPRITE_WARRIOR_HIT_0, 100 },
			{ SPRITE_WARRIOR_HIT_1, 100 }
		},
		.frame_count = 2
	},
	[ANIM_WARRIOR_DEAD] = {
		.frames = {
			{ SPRITE_WARRIOR_DEAD_0, 100 },
			{ SPRITE_WARRIOR_DEAD_1, 100 },
			{ SPRITE_WARRIOR_DEAD_2, 100 },
			{ SPRITE_WARRIOR_DEAD_3, 100 },
			{ SPRITE_WARRIOR_DEAD_4, 100 },
			{ SPRITE_WARRIOR_DEAD_5, 100 },
			{ SPRITE_WARRIOR_DEAD_6, 100 },
			{ SPRITE_WARRIOR_DEAD_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_IDLE] = {
		.frames = {
			{ SPRITE_HERO_IDLE_0, 100 },
			{ SPRITE_HERO_IDLE_1, 100 },
			{ SPRITE_HERO_IDLE_2, 100 },
			{ SPRITE_HERO_IDLE_3, 100 },
			{ SPRITE_HERO_IDLE_4, 100 }
		},
		.frame_count = 5
	},
	[ANIM_HERO_MOVE_LEFT] = {
		.frames = {
			{ SPRITE_HERO_MOVE_LEFT_0, 100 },
			{ SPRITE_HERO_MOVE_LEFT_1, 100 },
			{ SPRITE_HERO_MOVE_LEFT_2, 100 },
			{ SPRITE_HERO_MOVE_LEFT_3, 100 }
		},
		.frame_count = 4
	},
	[ANIM_HERO_MOVE_DOWN] = {
		.frames = {
			{ SPRITE_HERO_MOVE_DOWN_0, 100 },
			{ SPRITE_HERO_MOVE_DOWN_1, 100 },
			{ SPRITE_HERO_MOVE_DOWN_2, 100 },
			{ SPRITE_HERO_MOVE_DOWN_3, 100 },
			{ SPRITE_HERO_MOVE_DOWN_4, 100 },
			{ SPRITE_HERO_MOVE_DOWN_5, 100 },
			{ SPRITE_HERO_MOVE_DOWN_6, 100 },
			{ SPRITE_HERO_MOVE_DOWN_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_MOVE_UP] = {
		.frames = {
			{ SPRITE_HERO_MOVE_UP_0, 100 },
			{ SPRITE_HERO_MOVE_UP_1, 100 },
			{ SPRITE_HERO_MOVE_UP_2, 100 },
			{ SPRITE_HERO_MOVE_UP_3, 100 },
			{ SPRITE_HERO_MOVE_UP_4, 100 },
			{ SPRITE_HERO_MOVE_UP_5, 100 },
			{ SPRITE_HERO_MOVE_UP_6, 100 },
			{ SPRITE_HERO_MOVE_UP_7, 100 }
		},
		.frame_count = 8
	},
	[ANIM_HERO_HIT] = {
		.frames = {
			{ SPRITE_HERO_HIT_0, 100 },
			{ SPRITE_HERO_HIT_1, 100 }
		},
		.frame_count = 2
	},
	[ANIM_HERO_DEAD] = {
		.frames = {
			{ SPRITE_HERO_DEAD_0, 100 },
			{ SPRITE_HERO_DEAD_1, 100 },
			{ SPRITE_HERO_DEAD_2, 100 },
			{ SPRITE_HERO_DEAD_3, 100 },
			{ SPRITE_HERO_DEAD_4, 100 },
			{ SPRITE_HERO_DEAD_5, 100 },
			{ SPRITE_HERO_DEAD_6, 100 },
			{ SPRITE_HERO_DEAD_7, 100 },
			{ SPRITE_HERO_DEAD_8, 100 },
			{ SPRITE_HERO_DEAD_9, 100 }
		},
		.frame_count = 10
	}
};