#pragma once

enum EntityType {
    ENTITY_TYPE_UNKNOWN,
    ENTITY_TYPE_PLAYER,
    ENTITY_TYPE_GUN,
    ENTITY_TYPE_WARRIOR,
    ENTITY_TYPE_PROJECTILE,
    ENTITY_TYPE_BLOCK,
    ENTITY_TYPE_BOAR,
    ENTITY_TYPE_BOAR_MEAT,
    ENTITY_TYPE_IRON_DEPOSIT,
    ENTITY_TYPE_IRON,
    ENTITY_TYPE_PLANT_CORN,
    ENTITY_TYPE_ITEM_CORN,
    ENTITY_TYPE_CHEST_IRON,
    ENTITY_TYPE_ROBOT_GATHERER,
    ENTITY_TYPE_LANDING_POD_YELLOW,
    ENTITY_TYPE_COUNT
};
